/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cisneros;

/**
 *
 * @author Jose Maria
 */
public class VentanaConectarBase extends javax.swing.JInternalFrame {

    private Object MenuGestionLocalBD;

  

    /**
     * Creates new form conectarBase
     */
    
    public VentanaConectarBase() {
        initComponents();
        
        if(RadioConexionRed.isSelected()== true) {
            CheckActivaMood.setEnabled(true);
            CheckChamiloConexion.setEnabled(true);
            CheckOscConexion.setEnabled(true);
            
        
            if(CheckActivaMood.isSelected()== false) {
                TextoMoodUsuario.setEnabled(false);
                TextoPassMood.setEnabled(false);
                TextoDireccionMood.setEnabled(false);
            }else {
                TextoMoodUsuario.setEnabled(true);
                TextoPassMood.setEnabled(true);
                TextoDireccionMood.setEnabled(true);
            }
            if(CheckChamiloConexion.isSelected()== false) {
                TextoUsuarioChamilo.setEnabled(false);
                TextoPassChamilo.setEnabled(false);
                TextoDireccionChamilo.setEnabled(false);
            }else {
                TextoUsuarioChamilo.setEnabled(true);
                TextoPassChamilo.setEnabled(true);
                TextoDireccionChamilo.setEnabled(true);
            }
            if(CheckOscConexion.isSelected()== false) {
                TextoUsuarioOsc.setEnabled(false);
                TextoPassOsc.setEnabled(false);
                TextoDireccionOsc.setEnabled(false);
            } else {
                TextoUsuarioOsc.setEnabled(true);
                TextoPassOsc.setEnabled(true);
                TextoDireccionOsc.setEnabled(true);  
            }
        } else {
            CheckActivaMood.setEnabled(false);
            CheckChamiloConexion.setEnabled(false);
            CheckOscConexion.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextoUsuarioOsc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextoDireccionOsc = new javax.swing.JTextField();
        TextoPassOsc = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        CheckOscConexion = new javax.swing.JCheckBox();
        RadioConexionLocal = new javax.swing.JRadioButton();
        RadioConexionRed = new javax.swing.JRadioButton();
        BotonCerrarConexionBD = new javax.swing.JButton();
        BotonGuardarConexionBD = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Conexion Bases de Datos");
        setToolTipText("Conecte las bases de datos para gestionar alumnos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Cisneros/iconos/carpeta.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conexión OsCommerce"));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        TextoDireccionOsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDireccionOscActionPerformed(evt);
            }
        });

        jLabel3.setText("Dirección:");

        CheckOscConexion.setText("Activar conexión");
        CheckOscConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOscConexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckOscConexion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TextoUsuarioOsc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoPassOsc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoDireccionOsc, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckOscConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextoUsuarioOsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoPassOsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoDireccionOsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16))
        );

        buttonGroup1.add(RadioConexionLocal);
        RadioConexionLocal.setText("Conexion Local");
        RadioConexionLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioConexionLocalActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioConexionRed);
        RadioConexionRed.setSelected(true);
        RadioConexionRed.setText("Conexion Red");
        RadioConexionRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioConexionRedActionPerformed(evt);
            }
        });

        BotonCerrarConexionBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cisneros/iconos/cerrar.png"))); // NOI18N
        BotonCerrarConexionBD.setText("Cerrar");
        BotonCerrarConexionBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarConexionBDActionPerformed(evt);
            }
        });

        BotonGuardarConexionBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cisneros/iconos/guardar-datos.png"))); // NOI18N
        BotonGuardarConexionBD.setText("Guardar");
        BotonGuardarConexionBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarConexionBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonGuardarConexionBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonCerrarConexionBD))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(RadioConexionRed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(RadioConexionLocal))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioConexionRed)
                    .addComponent(RadioConexionLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCerrarConexionBD)
                    .addComponent(BotonGuardarConexionBD))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setBounds(0, 0, 588, 281);
    }// </editor-fold>//GEN-END:initComponents

    private void RadioConexionLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioConexionLocalActionPerformed
        if(RadioConexionLocal.isSelected()== true) {
            CheckActivaMood.setEnabled(false);
            CheckChamiloConexion.setEnabled(false);
            CheckOscConexion.setEnabled(false);
            TextoMoodUsuario.setEnabled(false);
            TextoPassMood.setEnabled(false);
            TextoDireccionMood.setEnabled(false);
            TextoUsuarioChamilo.setEnabled(false);
            TextoPassChamilo.setEnabled(false);
            TextoDireccionChamilo.setEnabled(false);
            TextoUsuarioOsc.setEnabled(false);
            TextoPassOsc.setEnabled(false);
            TextoDireccionOsc.setEnabled(false);
         }
    }//GEN-LAST:event_RadioConexionLocalActionPerformed

    private void BotonCerrarConexionBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarConexionBDActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonCerrarConexionBDActionPerformed

    private void CheckOscConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOscConexionActionPerformed
      if(CheckOscConexion.isSelected()== false) {
        TextoUsuarioOsc.setEnabled(false);
        TextoPassOsc.setEnabled(false);
        TextoDireccionOsc.setEnabled(false);
      } else {
        TextoUsuarioOsc.setEnabled(true);
        TextoPassOsc.setEnabled(true);
        TextoDireccionOsc.setEnabled(true);  
      }
    }//GEN-LAST:event_CheckOscConexionActionPerformed
    }
    
    private void RadioConexionRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioConexionRedActionPerformed
       if(RadioConexionRed.isSelected()== true) {
            CheckActivaMood.setEnabled(true);
            CheckChamiloConexion.setEnabled(true);
            CheckOscConexion.setEnabled(true);
            
        
            if(CheckActivaMood.isSelected()== false) {
                TextoMoodUsuario.setEnabled(false);
                TextoPassMood.setEnabled(false);
                TextoDireccionMood.setEnabled(false);
            }else {
                TextoMoodUsuario.setEnabled(true);
                TextoPassMood.setEnabled(true);
                TextoDireccionMood.setEnabled(true);
            }
            if(CheckChamiloConexion.isSelected()== false) {
                TextoUsuarioChamilo.setEnabled(false);
                TextoPassChamilo.setEnabled(false);
                TextoDireccionChamilo.setEnabled(false);
            }else {
                TextoUsuarioChamilo.setEnabled(true);
                TextoPassChamilo.setEnabled(true);
                TextoDireccionChamilo.setEnabled(true);
            }
            if(CheckOscConexion.isSelected()== false) {
                TextoUsuarioOsc.setEnabled(false);
                TextoPassOsc.setEnabled(false);
                TextoDireccionOsc.setEnabled(false);
            } else {
                TextoUsuarioOsc.setEnabled(true);
                TextoPassOsc.setEnabled(true);
                TextoDireccionOsc.setEnabled(true);  
            }
        } /* else {
            CheckActivaMood.setEnabled(false);
            CheckChamiloConexion.setEnabled(false);
            CheckOscConexion.setEnabled(false);
        } */
    }//GEN-LAST:event_RadioConexionRedActionPerformed

    private void BotonGuardarConexionBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarConexionBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarConexionBDActionPerformed

    private void TextoDireccionOscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDireccionOscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDireccionOscActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrarConexionBD;
    private javax.swing.JButton BotonGuardarConexionBD;
    private javax.swing.JCheckBox CheckOscConexion;
    private javax.swing.JRadioButton RadioConexionLocal;
    private javax.swing.JRadioButton RadioConexionRed;
    private javax.swing.JTextField TextoDireccionOsc;
    private javax.swing.JPasswordField TextoPassOsc;
    private javax.swing.JTextField TextoUsuarioOsc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
