/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cisneros;

import static java.lang.Double.parseDouble;

/**
 *
 * @author Jose Maria
 */
public class VentanaCalculadora extends javax.swing.JInternalFrame {
    
    /* Datos para la calculadora */
    String memoria1;
    String signo;
    String memoria2;
    
    public static boolean existepunto(String cadena){
        boolean resultado;
        resultado = false;
        
        for(int i=0; i< cadena.length(); i++) {
            if(cadena.substring(i,i+1).equals(".")) {
                resultado = true;
                break;
            }
        }
        return resultado;
    }
    
    public static String calculadora(String memoria1, String memoria2, String signo)
    {
        Double resultado = 0.0;
        String respuesta;
        
        if(signo.equals("-")){
            resultado=Double.parseDouble(memoria1)-Double.parseDouble(memoria2);
        }
        if(signo.equals("+")){
            resultado=Double.parseDouble(memoria1)+Double.parseDouble(memoria2);
        }
        if(signo.equals("*")){
            resultado=Double.parseDouble(memoria1)*Double.parseDouble(memoria2);
        }
        if(signo.equals("/")){
            resultado=Double.parseDouble(memoria1)/Double.parseDouble(memoria2);
        }
        if(signo.equals("P")){
            resultado=(Double.parseDouble(memoria1)*Double.parseDouble(memoria2)/100);
        }
        respuesta = resultado.toString();
        return respuesta;
    }

    
    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaCalculadora = new javax.swing.JTextField();
        BotonBorrarCalculadora = new javax.swing.JButton();
        CalculadoraCero = new javax.swing.JButton();
        CalculadoraCero2 = new javax.swing.JButton();
        calculadoraUno = new javax.swing.JButton();
        CalculadoraComa = new javax.swing.JButton();
        CalculadoraDos = new javax.swing.JButton();
        CalculadoraTres = new javax.swing.JButton();
        CalculadoraCuatro = new javax.swing.JButton();
        CalculadoraCinco = new javax.swing.JButton();
        Calculadora6 = new javax.swing.JButton();
        CalculadoraSiete = new javax.swing.JButton();
        CalculadoraOcho = new javax.swing.JButton();
        Calculadora9 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        BotonCalculadoraPorciento = new javax.swing.JButton();
        BotonBorrarCalculadora1 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Calculadora");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Cisneros/iconos/calculadora.png"))); // NOI18N

        PantallaCalculadora.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PantallaCalculadora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        BotonBorrarCalculadora.setBackground(new java.awt.Color(255, 153, 153));
        BotonBorrarCalculadora.setText("CE");
        BotonBorrarCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarCalculadoraActionPerformed(evt);
            }
        });

        CalculadoraCero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraCero.setText("0");
        CalculadoraCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraCeroActionPerformed(evt);
            }
        });

        CalculadoraCero2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraCero2.setText("00");
        CalculadoraCero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraCero2ActionPerformed(evt);
            }
        });

        calculadoraUno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calculadoraUno.setText("1");
        calculadoraUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraUnoActionPerformed(evt);
            }
        });

        CalculadoraComa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraComa.setText(".");
        CalculadoraComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraComaActionPerformed(evt);
            }
        });

        CalculadoraDos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraDos.setText("2");
        CalculadoraDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraDosActionPerformed(evt);
            }
        });

        CalculadoraTres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraTres.setText("3");
        CalculadoraTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraTresActionPerformed(evt);
            }
        });

        CalculadoraCuatro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraCuatro.setText("4");
        CalculadoraCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraCuatroActionPerformed(evt);
            }
        });

        CalculadoraCinco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraCinco.setText("5");
        CalculadoraCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraCincoActionPerformed(evt);
            }
        });

        Calculadora6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Calculadora6.setText("6");
        Calculadora6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora6ActionPerformed(evt);
            }
        });

        CalculadoraSiete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraSiete.setText("7");
        CalculadoraSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraSieteActionPerformed(evt);
            }
        });

        CalculadoraOcho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CalculadoraOcho.setText("8");
        CalculadoraOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraOchoActionPerformed(evt);
            }
        });

        Calculadora9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Calculadora9.setText("9");
        Calculadora9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora9ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton16.setText("=");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton17.setText("-");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton18.setText("x");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton19.setText("/");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        BotonCalculadoraPorciento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonCalculadoraPorciento.setText("%");
        BotonCalculadoraPorciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculadoraPorcientoActionPerformed(evt);
            }
        });

        BotonBorrarCalculadora1.setBackground(new java.awt.Color(255, 153, 153));
        BotonBorrarCalculadora1.setText("C");
        BotonBorrarCalculadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarCalculadora1ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton20.setText("+");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PantallaCalculadora)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CalculadoraSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CalculadoraOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Calculadora9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonCalculadoraPorciento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonBorrarCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotonBorrarCalculadora1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculadoraUno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CalculadoraDos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CalculadoraTres, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CalculadoraCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CalculadoraCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Calculadora6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CalculadoraCero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CalculadoraCero2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CalculadoraComa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PantallaCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonBorrarCalculadora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBorrarCalculadora)
                    .addComponent(CalculadoraSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculadoraOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculadora9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCalculadoraPorciento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculadoraCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculadoraCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculadora6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculadoraUno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculadoraDos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculadoraTres, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CalculadoraCero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CalculadoraCero2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CalculadoraComa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculadoraUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraUnoActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"1");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_calculadoraUnoActionPerformed

    private void CalculadoraDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraDosActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"2");
    }//GEN-LAST:event_CalculadoraDosActionPerformed

    private void CalculadoraTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraTresActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"3");   
    }//GEN-LAST:event_CalculadoraTresActionPerformed

    private void CalculadoraCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraCeroActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"0");   
    }//GEN-LAST:event_CalculadoraCeroActionPerformed

    private void CalculadoraCero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraCero2ActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"00");  
    }//GEN-LAST:event_CalculadoraCero2ActionPerformed

    private void CalculadoraComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraComaActionPerformed
        String cadena;
        cadena=PantallaCalculadora.getText();
        if(cadena.length()<=0) {
            PantallaCalculadora.setText("0.");
        } else {
            if(!existepunto(PantallaCalculadora.getText())) {
                PantallaCalculadora.setText(PantallaCalculadora.getText()+".");
            }
            
        }
        
    }//GEN-LAST:event_CalculadoraComaActionPerformed

    private void CalculadoraCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraCuatroActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"4");        
    }//GEN-LAST:event_CalculadoraCuatroActionPerformed

    private void CalculadoraCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraCincoActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"5");
    }//GEN-LAST:event_CalculadoraCincoActionPerformed

    private void Calculadora6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora6ActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"6");
    }//GEN-LAST:event_Calculadora6ActionPerformed

    private void CalculadoraSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraSieteActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"7");
    }//GEN-LAST:event_CalculadoraSieteActionPerformed

    private void CalculadoraOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraOchoActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"8");
    }//GEN-LAST:event_CalculadoraOchoActionPerformed

    private void Calculadora9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora9ActionPerformed
        PantallaCalculadora.setText(PantallaCalculadora.getText()+"9");
    }//GEN-LAST:event_Calculadora9ActionPerformed

    private void BotonBorrarCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarCalculadoraActionPerformed
        PantallaCalculadora.setText("");
    }//GEN-LAST:event_BotonBorrarCalculadoraActionPerformed

    private void BotonBorrarCalculadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarCalculadora1ActionPerformed
        String cadena;
        cadena=PantallaCalculadora.getText();
        
        if(cadena.length()>0) {
            cadena = cadena.substring(0, cadena.length()-1);
            PantallaCalculadora.setText(cadena);
        } 
    }//GEN-LAST:event_BotonBorrarCalculadora1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        
        if(!PantallaCalculadora.getText().equals("")) {
            memoria1=PantallaCalculadora.getText();
            signo = "-";
            PantallaCalculadora.setText("");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
     if(!PantallaCalculadora.getText().equals("")) {
            memoria1=PantallaCalculadora.getText();
            signo = "*";
            PantallaCalculadora.setText("");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if(!PantallaCalculadora.getText().equals("")) {
            memoria1=PantallaCalculadora.getText();
            signo = "/";
            PantallaCalculadora.setText("");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String resultado;
        memoria2 = PantallaCalculadora.getText();
        if(!memoria2.equals("")) {
            resultado = calculadora(memoria1,memoria2,signo);
            PantallaCalculadora.setText(resultado);
        }
    
    }//GEN-LAST:event_jButton16ActionPerformed

    private void BotonCalculadoraPorcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculadoraPorcientoActionPerformed
       if(!PantallaCalculadora.getText().equals("")) {
            memoria1=PantallaCalculadora.getText();
            signo = "P";
            PantallaCalculadora.setText("");
        }
    }//GEN-LAST:event_BotonCalculadoraPorcientoActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        if(!PantallaCalculadora.getText().equals("")) {
            memoria1=PantallaCalculadora.getText();
            signo = "+";
            PantallaCalculadora.setText("");
        }
    }//GEN-LAST:event_jButton20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrarCalculadora;
    private javax.swing.JButton BotonBorrarCalculadora1;
    private javax.swing.JButton BotonCalculadoraPorciento;
    private javax.swing.JButton Calculadora6;
    private javax.swing.JButton Calculadora9;
    private javax.swing.JButton CalculadoraCero;
    private javax.swing.JButton CalculadoraCero2;
    private javax.swing.JButton CalculadoraCinco;
    private javax.swing.JButton CalculadoraComa;
    private javax.swing.JButton CalculadoraCuatro;
    private javax.swing.JButton CalculadoraDos;
    private javax.swing.JButton CalculadoraOcho;
    private javax.swing.JButton CalculadoraSiete;
    private javax.swing.JButton CalculadoraTres;
    private javax.swing.JTextField PantallaCalculadora;
    private javax.swing.JButton calculadoraUno;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    // End of variables declaration//GEN-END:variables
}
